version: '3'

services:
  backend:
    container_name: danke_backend
#    image: opentreehole/backend:latest
    build:
      args:
        - SERVICE_NAME=danke
    environment:
      - DB_TYPE=mysql
      - DB_URL=cb:cb@tcp(db:3306)/danke?parseTime=true
    volumes:
      - data:/app/data
    ports:
      - "10580:8000"

  db:
    container_name: danke_db
    image: mysql:8.0
#    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: danke
      MYSQL_USER: cb
      MYSQL_PASSWORD: cb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  data:
    name: danke_data
  db_data:
    name: danke_db_data