mode: dev
port: 8000
debug: true

db:
    type: sqlite
    dsn: data/sqlite.db
    replicas: [ ]

cache:
    type: "memory"
    url: ""
    db: 0
    username: ""
    password: ""

email:
    host: ""
    port: 0
    username: ""
    password: ""
    from: ""
    fromName: ""
    devEmail: ""
    siteName: ""
    tls: false
    whitelist: [ ]

feature:
    standalone: true
    emailNotification: false
    emailVerification: false
    registrationTest: false
    shamir: false
    verificationCodeExpires: 0

gateway:
    token: ""
    type: ""
    url: ""

notification:
    androidPackageName: ""
    apnsKeyPath: ""
    iosPackageName: ""
    mipushCallbackUrl: ""
    mipushKeyPath: ""

searchEngine:
    type: ""
    url: ""

service:
    auth: ""
    notification: ""
